image: lightandlight/purescript:0.11.5

stages:
  - install
  - build
  - test
  - github
  - publish
  
install:
  stage: install
  script:
    - bower install
  cache:
    paths:
      - bower_components/

build:
  stage: build
  script:
    - pulp build
  cache:
    paths:
      - bower_components
      - output/
    
test:
  stage: test
  script:
    - pulp test
    - pulp version
    
github:
  stage: github
  script:
    - git push https://lightandlight:$GITHUB_TOKEN@github.com/lightandlight/purescript-records.git
    
# publish:
#   stage: publish
#   script:
#     - echo "$GITHUB_TOKEN" | pulp login
#     - pulp publish